### ISSUE TITLE
這是已經完成的代碼嗎？

### ISSUE THREAD

**Issue by Christian-lyc** [kairos03/ProxylessNAS-Pytorch#1]
如題

**Comment by kairos03** [comment]
Please use english. I'm not chinese, it is very rude.

**Comment by Christian-lyc** [comment]
sorry，I didn't notice that. I just want to make sure whether this proxylessNAS is a finished one.

**Comment by kairos03** [comment]
Except Latency loss, code is done. Loss also implemted in a week. If you want to check progress, please read README.md. Thank you.
