### ISSUE TITLE
About Gate

### ISSUE THREAD

**Issue by hixiaye** [kairos03/ProxylessNAS-Pytorch#3]
Thanks for your code.
I didn't find the gate and the gradient in Equation(4) in your code.
Would you please elaborate on it?
thx

**Comment by kairos03** [comment]
Hello,
thank you for issue.
Could you check below code. If it is not correct let me know how to fix. 
Thank you.

https://github.com/kairos03/ProxylessNAS-Pytorch/blob/c87b233aaffb9e38329cbb7d4fc5f5398b1312a8/proxylessnas/architect.py#L88-L96
